### ISSUE TITLE
With Vue-router: component is a fragment instance

### ISSUE THREAD

**Issue by nerijunior** [vuejs/vue-webpack-meteor-example#13]
I got this error when using vue-router:

`Attribute "id" is ignored on component <div> because the component is a fragment instance:`

index.html

``` html
<body>
    <div id="app"></div>
</body>
```

main.js

``` javascript
Vue = require('vue')
VueRouter = require('vue-router')
Vue.use(VueRouter)

Template.body.onRendered(function(){
  router.start(App, '#app');
});
```

app.vue:

``` javascript
module.exports = Vue.extend({
  template : '<router-view></router-view>',
  data : function(){
    return {
      version : '1.0.0'
    };
  },
  components : {
    'layout' : require('./defaults/layout.vue')
  }
})
```

I've tried some alternatives without success, some idea?

**Comment by jpokrzyk** [comment]
http://vuejs.org/guide/components.html#Fragment-Instance

You can't have a component as your top level element in the template. Wrap router-view with a div tag.

`template : '<div><router-view></router-view></div>',`

But since you're not really using any vue single file component syntax you should just move the app.vue logic over to your main.js.

This isn't the place for this sort of question though. Post it on the forum or gitter.
